spring:
profiles: h2
jpa:
database-platform: org.hibernate.dialect.H2Dialect
datasource:
url: jdbc:h2:mem:liquibasedemo
driverClassName: org.h2.Driver
username: demouser
password: demopassword
liquibase:
parameters:
textColumnType: VARCHAR(250)
contexts: nonprod
h2:
console:
enabled: true